name: General purpose Gradle CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Validate JSON
      run: ./gradlew validate
